### ISSUE TITLE
Migrate from MongoDB to PostgreSQL using Airbyte

### ISSUE THREAD

**Issue by iKausik** [airbytehq/write-for-the-community#153]
**Submission Details**

How to migrate data from MongoDB local database to PostgreSQL local database using Airbyte

**The Format**

- [x] Blog Article
- [x] Tutorial
- [ ] Video

**Comment by iKausik** [comment]
Hi @arimbr, I would like to work on this topic

**Comment by iKausik** [comment]
Hi @arimbr, I would like to write this.

**Comment by arimbr** [comment]
Hi @iKausik. That's an interesting topic! Thanks for the submission :)

You can definitely use Airbyte to migrate from MongoDB to PostgreSQL. Otherwise, Airbyte is most commonly used as a data replication tool (instead of data migration) where you continuously replicate data from the source to the destination, without decommissioning the source.

Could you share a bit about your experience with this topic?

Do you have a published piece of content that I could check?

**Comment by iKausik** [comment]
Hi, @arimbr, I've full-stack development experience with PostgreSQL, I believe I can do it. I recently started writing Technical articles, I've just submitted one for Twilio, you can check that. I sent the link on the slack message.

**Comment by arimbr** [comment]
Hi, @iKausik thanks for the info! We are about to relaunch the Write for the Community Program and update the application process. To start we will focus on writers that are data engineers, ideally have some experience with Airbyte, and have published articles about data engineering. I know we are asking a lot, but to provide the best experience to writers, I cannot take in your application for this topic at the moment.

For the record [here](https://www.voucherify.io/tech/how-we-moved-from-mongodb-to-postgres-without-downtime-and-cut-our-costs-by-30) is a very complete article about migrating from MongoDB to PostgreSQL that shows some of the edge cases. For this topic, we would ideally take in someone who has previously migrated data from MongoDB to PostgreSQL.

**Comment by iKausik** [comment]
Thank you for your feedback @arimbr. Is there anything else I can work on for Airbyte?
