### ISSUE TITLE
Airbyte's 1st anniversary - a look back

### ISSUE THREAD

**Issue by johnlafleur** [airbytehq/write-for-the-community#73]

**Comment by arimbr** [comment]
Hi @johnlafleur ! Does this card references this published article https://airbyte.io/blog/airbyte-is-turning-1?

**Comment by arimbr** [comment]
@avaidyanatha This issue is on the "Submitted" column in the Github Project. What does that column mean?

I added an extra column "To Review" that should include all articles that we got a draft for and are currently under review.

I would also like to replace the "Submitted" column with a "To Publish" to include all articles that have been reviewed and we are waiting to load them into the CMS. Is that ok for you?

**Comment by johnlafleur** [comment]
Indeed! I think we can close it.

**Comment by avaidyanatha** [comment]
Yep, closing now.
